
GET http://localhost:1234/


### 
GET http://localhost:1234/users
Content-Type: application/x-www-form-urlencoded

&page=2
&pageSize=10
&user=diamedez diaz


### 
GET http://localhost:1234/users
Content-Type: application/json

{
  "page": 2,
  "pageSize": 10,
  "user": 9
}

###

GET http://localhost:1234/user/nameuser


###

POST http://localhost:1234/user/register
Content-Type: application/json

{
  "username": "nameuser",
  "password": "123456789",
  "email":"correo@gmail.com",
  "phone": "2548957525",
  "firstName" : "Jack",
  "lastName" : "Ardila",
  "imgPhoto" : null,
  "age": 24,
  "isAdult": true
}

### 

