openapi: 3.0.1
info:
  title: Swagger ESPOT API
  description:
    "Peticione par conectar el front con el back"
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: http://localhost:1234/
tags:
  - name: user
    description: Operaciones con el usuario
paths:
  /auth/register:
    post:
      tags:
        - user
      summary: crear usuario
      description: Forma de la peticion para crear un nuevoi usuario.
      operationId: createUser
      requestBody:
        description: objeto para crear usuario
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/User"
          "application/x-www-form-urlencoded":
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: Creacion de usuario correcto
          content: {
            "application/json" : {}
          }
        '422':
          description: Error con el formato de la peticion
          content:
            'application/json': {}
      x-codegen-request-body-name: body
  /auth/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
      requestBody:  # Se agregó el cuerpo de la solicitud
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      parameters:  # Parámetros eliminados ya que ahora se usan en el cuerpo
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          headers:
            X-Rate-Limit:
              description: Calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: Date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
          content: {}
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: {}
  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: "The name that needs to be fetched. Use user1 for testing. "
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Updated user object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: pruebas1234
        firstName:
          type: string
          example: pepito
        lastName:
          type: string
          example: perez
        email:
          type: string
          example: emailpepito@gmail.com
        password:
          type: string
          example: 123456789
        phone:
          type: string
          example: 3005558877
        age:
          type: number
          format: int32
          example: 17
        isAdult: 
          type: boolean
          example: false
          description: mayor a 18 años es mayor de edad
        userStatus:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User