### traer todas la peliculas
GET http://localhost:1234/movies

### traer todas la peliculas con paginacion
GET http://localhost:1234/movies?pag=1


### pedir peliculas con un filtro de genero
GET http://localhost:1234/movies?genero=action

### crear una pelicula 
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "pruebas",
  "year" : 2024,
  "director" : "Jhohanes Burgo",
  "duration" : 20,
  "rate" : 9.9,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
PATCH http://localhost:1234/movies/9e6106f0-848b-4810-a11a-3d832a5610f9
Content-Type: application/json

{
  "year": 2010
}


### Eliminar una peli
DELETE  http://localhost:1234/movies/9e6106f0-848b-4810-a11a-3d832a5610f9